skrypt:
		sh zad3.sh /home/jakun/skrypty/zad3/szkola /home/jakun/skrypty/zad3/usuniete-pliki.txt /home/jakun/skrypty/zad3/usuniete-katalogi.txt

testowepliki:
	mkdir -p szkola/liceum/{human,biolchem,matfiz}; mkdir -p szkola/technikum/{ti,tu,tr}; touch szkola/technikum/ti/tomek; touch szkola/liceum/human/agata
clear:
	rm -rf szkola/* usuniete-pliki.txt usuniete-katalogi.txt
